---
- hosts: localhost
  connection: local
  roles:
    - role: indigo-dc.galaxycloud-tools
      galaxy_flavor: 'galaxy-rna-workbench'
      move_datasets: false
      create_bootstrap_user: true
      Galaxy_flavor_recipe_branch: 'devel'
      when: galaxy_flavor != 'galaxy-no-tools'
