---
- hosts: localhost
  connection: local
  roles:
    - role: indigo-dc.galaxycloud-tools
      galaxy_flavor: 'galaxy-rna-workbench'
      move_datasets: false
      Galaxy_flavor_recipe_branch: 'devel'
      #create_bootstrap_user: true
